[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
tonic = "0.12.2"
prost = "0.13.3" # 用于生成 Protobuf
proto = { path = "../proto" }
tokio-stream = "0.1.16"
